# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-14 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
